#docker inspect contenedor

#Comando largo de docker run -->
#docker run -d -it --name mi-daw-12 net mi-red --ip 172.100.0.10 --mount source=mi-vol,target=/app/data -p 8080:80 ubuntu:22.04
#

#docker build -t <nombre> . --> crear
services:
  mi-mysql:
    image: mysql
    container_name: mi-mysql
    networks:
      mi-mysqlred:
        ipv4_address: 172.25.0.2
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - mi-mysql-vol:/var/lib/mysql

  mi-dashboard:
    image: phpmyadmin/phpmyadmin
    container_name: mi-dashboard
    networks:
      - mi-mysqlred
    environment:
      PMA_HOST: mi-mysql
    ports:
      - "8080:80"

networks:
  mi-mysqlred:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

volumes:
  mi-mysql-vol:
